stages:
  - cek


# upload job, see https://lftp.yar.ru/lftp-man.html
cek:
  stage: cek
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -c "set ftp:ssl-allow no; open -u $USER,$PASSWD $HOST; mirror -Rnev  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/ --exclude .env  "
  only:
    - cek
